name: Deploy to Firebase

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - 'firestore/**'
      - 'firebase.json'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for functions
        run: |
          cd functions
          npm install

      - name: Create Service Account Key File
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/service-account.json
        
      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json
          firebase deploy --only functions,firestore:rules --project arknights-sharing-view