name: Deploy to Firebase

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - 'firestore/**'
      - 'firebase.json'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          
      - name: Create ESLint configuration
        run: |
          cd functions
          if [ ! -f ".eslintrc.js" ]; then
            echo "Creating .eslintrc.js"
            cat > .eslintrc.js << EOF
module.exports = {
  root: true,
  env: {
    es6: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
  ],
  rules: {
    // 基本的なルールのみを適用
    "no-unused-vars": "warn",
  },
  parserOptions: {
    ecmaVersion: 2020,
  },
};
EOF
          fi
          cd ..

      - name: Create Service Account Key File
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/service-account.json
        
      - name: Install dependencies for functions
        run: |
          cd functions
          npm install
          cd ..
        
      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json
          firebase deploy --only functions,firestore:rules --project arknights-sharing-view